site_name: Civitan International Neuroimaging Laboratory
repo_url: https://github.com/UAB-CINL/UAB-CINL.github.io

theme:
  name: 'material'
  include_search_page: true
  search_index_only: true
  features:
    - tabs: true
    - navigation.indexes
    - toc.follow
  custom_dir: 'theme'

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - footnotes
  - lightgallery:
      show_description_in_lightgallery: true
      show_description_as_inline_caption: false
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search
  - table-reader:
      data_path: 'docs'

nav:
  - Home: index.md
  - Getting Started:
    - onboarding/index.md
  - Policies and Procedures: 
    - policies/index.md
  - Equipment and Facilities:
    - equipment/index.md
  - Data Management:
    - data/index.md
    - XNAT:
      data/xnat/index.md
  - How-To:
    - how-to/index.md
  - Image Preprocessing: 
    - preprocessing/index.md
    - BIDS: 
      - preprocessing/bids/index.md
      - preprocessing/bids/principles.md
      - preprocessing/bids/practical_heudiconv.md
      - preprocessing/bids/heudiconv_scripts.md
    - MRIQC: preprocessing/mriqc.md
    - fmriprep:
      - preprocessing/fmriprep/index.md
      - preprocessing/fmriprep/fmriprep-usage.md
      - preprocessing/fmriprep/fmriprep-scripts.md
    - qsiprep:
      - preprocessing/qsiprep/index.md
      - preprocessing/qsiprep/qsiprep_usage.md
    - HCP Pipelines: 
      - preprocessing/hcp_pipelines/index.md
      - Structural Pipeline: preprocessing/hcp_pipelines/structural_pipeline.md
  - Image Analysis:
    - Using CIFTI:
      - R:
        - Walkthrough: analysis/cifti/R/cifti-r.html
        - Example Analysis: analysis/cifti/R/cifti-example.html
    - NODDI: analysis/noddi.md
    - Resources: analysis/resources.md
  - Funding:
    - funding/index.md