site_name: Civitan International Neuroimaging Laboratory
repo_url: https://github.com/UAB-CINL/UAB-CINL.github.io

theme:
  name: 'material'
  include_search_page: true
  search_index_only: true
  features:
    - tabs: true
    - navigation.indexes
  custom_dir: 'theme'

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - lightgallery:
      show_description_in_lightgallery: true
      show_description_as_inline_caption: false
  - toc:
      permalink: true

plugins:
  - search
  - table-reader:
      data_path: 'docs'

nav:
  - Home: 'index.md'
  - Policies and Procedures:
    - Getting Started: scanner/getting_started.md
    - Onboarding: scanner/onboarding.md
    - Training: scanner/training.md
    - Scheduling and Billing: scanner/scheduling.md
    - Screening and Implants: scanner/implants.md
    - Data Transfer:
      - Local Transfer and OSIRIX: scanner/data_management.md
      - XNAT:
        - scanner/xnat/index.md
        - scanner/xnat/account.md
        - scanner/xnat/file_management.md
        - scanner/xnat/projects.md
  - MRI Preprocessing and Analysis:
    - BIDS: 
      - Introduction: analysis/bids/index.md
      - analysis/bids/principles.md
      - analysis/bids/practical-heudiconv.md
      - analysis/bids/heudiconv-scripts.md
    - MRIQC: analysis/mriqc.md
    - fmriprep:
      - Introduction: analysis/fmriprep/index.md
      - analysis/fmriprep/fmriprep-usage.md
      - analysis/fmriprep/fmriprep-scripts.md
    - Resources: analysis/resources.md
